### PR TITLE
Create goldbergjeffrey.md

### PR DESCRIPTION
**Pull request by goldbergjeffrey**

### CODE REVIEW

**Comment by stefanwalther** [comment]
Hi @goldbergjeffrey, thx. eMail received.

**Comment by ricsv** [comment]
@goldbergjeffrey Could you please resubmit this PR against the `master` branch? We didn't see it was put against the `cla-1.1` branch and accidentally merged. (Sry for the inconvenience).

**Comment by goldbergjeffrey** [comment]
please see #6

**Comment by ricsv** [comment]
Perfect, thanks!

**Pull request merged**
