### PR TITLE
    4/26/2017

### PR DESCRIPTION
**Pull request by mprorock**
04/26/2017

    By introducing this file I hereby agree to the terms of the Qlik R&D Contributors License
    Agreement, version 1.0, with MD5 checksum: e4ed5b420a8c9400390a55ac12dad65b.

    I furthermore declare that I am authorized and able to make this agreement.

    Signed,

    Michael Prorock
    https://github.com/mprorock

### CODE REVIEW

**Comment by peol** [comment]
Hi @mprorock, sorry for the late reply!

It looks like you commit is an empty file (and the content we expect in the file is here as a PR description), it would be great if you could update your PR commit to include that content. Thanks!

**Comment by mprorock** [comment]
updated

**Comment by peol** [comment]
Sorry for nitpicking, but you forgot the `[date]` template in the file: https://github.com/qlik-oss/open-source/blob/master/sign-cla.md#template

**Comment by mprorock** [comment]
Good catch, thanks!  I copied and pasted and it didn't grab the date

**Review by peol — APPROVED** [review]

**Pull request merged**
